/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/paceCalc/PaceInputs`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TimeInput`; params?: Router.UnknownInputParams; } | { pathname: `/../components/paceCalc/TimeInputRow`; params?: Router.UnknownInputParams; } | { pathname: `/../components/paceCalc/PaceInputRow`; params?: Router.UnknownInputParams; } | { pathname: `/../components/paceCalc/DistanceInputRow`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/paceCalc/services/paceInputUtils`; params?: Router.UnknownInputParams; } | { pathname: `/../components/paceCalc/CalcButton`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pace` | `/pace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/timeCalc` | `/timeCalc`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/paceCalc/PaceInputs`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TimeInput`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/paceCalc/TimeInputRow`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/paceCalc/PaceInputRow`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/paceCalc/DistanceInputRow`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/paceCalc/services/paceInputUtils`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/paceCalc/CalcButton`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pace` | `/pace`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/timeCalc` | `/timeCalc`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/paceCalc/PaceInputs${`?${string}` | `#${string}` | ''}` | `/../components/TimeInput${`?${string}` | `#${string}` | ''}` | `/../components/paceCalc/TimeInputRow${`?${string}` | `#${string}` | ''}` | `/../components/paceCalc/PaceInputRow${`?${string}` | `#${string}` | ''}` | `/../components/paceCalc/DistanceInputRow${`?${string}` | `#${string}` | ''}` | `/../lib/paceCalc/services/paceInputUtils${`?${string}` | `#${string}` | ''}` | `/../components/paceCalc/CalcButton${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pace${`?${string}` | `#${string}` | ''}` | `/pace${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/timeCalc${`?${string}` | `#${string}` | ''}` | `/timeCalc${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/paceCalc/PaceInputs`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TimeInput`; params?: Router.UnknownInputParams; } | { pathname: `/../components/paceCalc/TimeInputRow`; params?: Router.UnknownInputParams; } | { pathname: `/../components/paceCalc/PaceInputRow`; params?: Router.UnknownInputParams; } | { pathname: `/../components/paceCalc/DistanceInputRow`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/paceCalc/services/paceInputUtils`; params?: Router.UnknownInputParams; } | { pathname: `/../components/paceCalc/CalcButton`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pace` | `/pace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/timeCalc` | `/timeCalc`; params?: Router.UnknownInputParams; };
    }
  }
}
